# Generated by Django 3.1.14 on 2025-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(default='default_pokemon.png', null=True, upload_to=''),
        ),
    ]
