# Generated by Django 3.1.14 on 2025-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20250115_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='next_evolution',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='previous_evolution',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
