# Generated by Django 3.1.14 on 2025-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20250115_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolutions',
            field=models.ManyToManyField(blank=True, related_name='previous_evolutions', to='pokemon_entities.Pokemon'),
        ),
    ]
