# Generated by Django 3.1.14 on 2025-01-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20250115_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolutions',
            new_name='next_evolution',
        ),
    ]
