# Generated by Django 3.1.14 on 2025-01-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20250115_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolved_from',
            new_name='previous_evolution',
        ),
    ]
