# Generated by Django 3.1.14 on 2025-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20250116_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='health',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='stamina',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время исчезновения'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
